/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sergo.tictactoe;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        AppLauncher classUnderTest = AppLauncher.getInstance();
        assertNotNull("app should have a greeting","TEST");
    }
}
